

GET http://localhost:4000/auth/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoieW9nZWUiLCJlbWFpbCI6InlvZ2VlMjkwNEBnbWFpbC5jb20iLCJpYXQiOjE2ODg5NjMyNjUsImV4cCI6MTY4OTU2ODA2NX0.rfPLbVgbjk2GxwDChyRrKL0zSwBQJViDygbSLPXEb5QALuI-bLXZGhxHz9TECYdc_bXeG96tJ3iry5WoLKQxpkbBJtsEXMMHQDOAWKD5REonP0tVYKUTb4qBxjRqb_UZWyJNySyR8fWVFNPaDcO_Ws446P7cKf28ihtqEDW8_HGxsfd8DGopVKfnML8FG3Yj_uV1LF1LDm7jvac4atOHgngyufnnF_lBdZAh0IdazNtR1CusREBRN7lkVTqDQJrOcLLfHTo8sAUJnOvpN6n6yPsAa1400JsP9F1soS0u8tDgj0YQXSpZOJHHsr0waeqoK1aQER-lKEM_K1B8L_dAd3TNiOwmw35Fw6KOts0MNizf17h24qZxRgNOuiPYmQS7u8RiCYC1bfPmyPVill733s8NUrqU50_t3m3cRhojB_8g9wBfBN0H7i4nCMuomx3m9TyAYq7lifCURhTnuF5r-mVrlb-4HiDWUTRNc2625Nq05JjNijZSmOVC0e81lgMQMKs9fGk0zgpbrvyc5_tlP0y8LglUKgS3QnjtVUHhBVI67s5_ED1562Qmo8sjzdlYs16_gGkcCrYA1finoT6QN_CsL-K_yvVPUH48eIilnisZBGG-vTBDbjFSTUgqygo22oSPNnBvy_PGw5Xa1SnrJy2oOK6cz4CyOz1sA2cDVVI

###

POST http://localhost:4000/auth/login 
Content-Type: application/json

{
   "email": "yogee2904@gmail.com", 
   "password": "abc"
}